name: Build

permissions:
  contents: write
  actions: write

inputs:
  model:
    required: true
    type: string
  soc:
    required: true
    type: string
  branch:
    required: true
    type: string
  manifest:
    required: true
    type: string
  android_version:
    required: true
    type: string
  kernel_version:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Validating inputs..."
        if [[ -z "${{ inputs.model }}" ]]; then
          echo "Error: model is required"
          exit 1
        fi
        if [[ -z "${{ inputs.soc }}" ]]; then
          echo "Error: soc is required"
          exit 1
        fi
        echo "✓ All inputs validated"

    - name: Setup Build System
      shell: bash
      run: |
        set -euo pipefail
        
        export DEBIAN_FRONTEND=noninteractive
        echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV

        echo "=== Initial disk space ==="
        df -h

        echo "Cleaning up unnecessary files and packages..."
        
        # Remove large directories
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc \
          /usr/local/.ghcup /opt/hostedtoolcache/CodeQL \
          /usr/local/share/powershell /usr/share/swift 2>/dev/null || true
        
        sudo docker image prune --all --force
        echo "✓ Large directories removed"

        # Remove unwanted packages
        sudo apt-get purge -y \
          aria2 ansible azure-cli shellcheck rpm xorriso zsync \
          esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
          google-cloud-sdk imagemagick \
          libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
          mercurial apt-transport-https mono-complete libmysqlclient \
          unixodbc-dev yarn chrpath libxft-dev \
          libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
          snmp pollinate libpq-dev postgresql-client powershell ruby-full \
          sphinxsearch subversion mongodb-org microsoft-edge-stable 2>/dev/null || true

        # Regex-based purges
        sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') 2>/dev/null || true

        # Clean up
        sudo apt-get autoremove -y
        sudo apt-get autoclean -y
        echo "✓ Packages purged"

        echo "=== Disk space after cleanup ==="
        df -h

        # Install dependencies (including build essentials)
        echo "Installing dependencies..."
        sudo apt-get update
        sudo apt-get install -y \
          python3 python-is-python3 ccache zip curl git \
          build-essential bc bison flex libssl-dev libelf-dev \
          libncurses-dev kmod cpio

        # Configure ccache
        export CCACHE_DIR=$GITHUB_WORKSPACE/ccache
        export CCACHE_MAXSIZE=5G
        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=6
        echo "CCACHE_DIR=$GITHUB_WORKSPACE/ccache" >> $GITHUB_ENV
        echo "CCACHE_MAXSIZE=5G" >> $GITHUB_ENV
        echo "CCACHE_COMPRESS=1" >> $GITHUB_ENV
        echo "CCACHE_COMPRESSLEVEL=6" >> $GITHUB_ENV
        
        mkdir -p $GITHUB_WORKSPACE/ccache
        ccache -z
        ccache -s
        echo "✓ ccache configured"

        # Setup repo tool
        mkdir -p ./git-repo
        curl -sSL https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
        chmod a+rx ./git-repo/repo
        echo "REPO=$GITHUB_WORKSPACE/./git-repo/repo" >> $GITHUB_ENV
        echo "✓ Repo tool installed"

        # Set CONFIG environment variable
        echo "CONFIG=${{ inputs.model }}" >> $GITHUB_ENV
        echo "✓ Build system setup complete"

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/ccache
        key: ccache-${{ inputs.model }}-${{ inputs.soc }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ inputs.model }}-${{ inputs.soc }}-
          ccache-${{ inputs.model }}-

    - name: Clone AnyKernel3
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Cloning AnyKernel3..."
        ANYKERNEL_BRANCH="gki-2.0"
        echo "Using branch for AnyKernel3: $ANYKERNEL_BRANCH"
        
        if [ -d "AnyKernel3" ]; then
          echo "AnyKernel3 already exists, pulling latest changes..."
          cd AnyKernel3
          git pull
          cd ..
        else
          git clone https://github.com/TheWildJames/AnyKernel3.git -b "$ANYKERNEL_BRANCH" --depth=1
        fi
        echo "✓ AnyKernel3 ready"

    - name: Initialize and Sync Kernel Source
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Creating folder for configuration: $CONFIG..."
        mkdir -p "$CONFIG"
        cd "$CONFIG"

        echo "Initializing kernel source repository..."
        
        if [[ "${{ inputs.manifest }}" == https://* ]]; then
          echo "Using custom manifest URL..."
          MANIFEST_NAME="temp_manifest.xml"
          mkdir -p .repo/manifests
          curl -fsSL ${{ inputs.manifest }} -o .repo/manifests/$MANIFEST_NAME
        else
          echo "Using manifest from repository..."
          MANIFEST_NAME="${{ inputs.manifest }}"
        fi
        
        $REPO init \
          -u https://github.com/OnePlusOSS/kernel_manifest.git \
          -b ${{ inputs.branch }} \
          -m "$MANIFEST_NAME" \
          --repo-rev=stable \
          --depth=1 \
          --no-clone-bundle \
          --no-tags

        # Filter out CLO repositories
        echo "Filtering inaccessible repositories..."
        MANIFEST_PATH=".repo/manifests/$MANIFEST_NAME"
        
        if [[ -f "$MANIFEST_PATH" ]]; then
          cp "$MANIFEST_PATH" "${MANIFEST_PATH}.backup"
          
          # Remove CLO entries
          sed -i '/<remote.*name="clo-la"/,/<\/remote>/d' "$MANIFEST_PATH" || true
          sed -i '/<remote.*git\.codelinaro\.org/d' "$MANIFEST_PATH" || true
          sed -i '/<project.*remote="clo-la"/d' "$MANIFEST_PATH" || true
          sed -i '/git\.codelinaro\.org/d' "$MANIFEST_PATH" || true
          
          echo "✓ Manifest filtered"
        fi

        echo "Repo version:"
        $REPO --version

        echo "Syncing kernel source (this may take a while)..."
        $REPO sync -c \
          --no-clone-bundle \
          --no-tags \
          --optimized-fetch \
          --prune \
          --force-sync \
          -j$(nproc --all) 2>&1 | tee sync.log || {
            echo "⚠️ Some repositories failed (expected for CLO)"
            echo "Checking what was synced..."
            $REPO list
          }

        echo "✓ Kernel source synced successfully"

    - name: Apply Kernel Configurations
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Changing to configuration directory: $CONFIG..."
        cd "$CONFIG/kernel_platform"

        echo "Applying LTO configurations..."
        
        # Apply to gki_defconfig
        if [ -f ./common/arch/arm64/configs/gki_defconfig ]; then
          if ! grep -q "CONFIG_LTO_CLANG_THIN=y" ./common/arch/arm64/configs/gki_defconfig; then
            echo "CONFIG_LTO_CLANG_THIN=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          if ! grep -q "CONFIG_LTO_CLANG=y" ./common/arch/arm64/configs/gki_defconfig; then
            echo "CONFIG_LTO_CLANG=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
        fi
        
        # Apply to vendor defconfig if exists
        VENDOR_DEFCONFIG="./msm-kernel/arch/arm64/configs/vendor/${{ inputs.soc }}_defconfig"
        if [ -f "$VENDOR_DEFCONFIG" ]; then
          echo "Applying LTO to vendor defconfig..."
          if ! grep -q "CONFIG_LTO_CLANG_THIN=y" "$VENDOR_DEFCONFIG"; then
            echo "CONFIG_LTO_CLANG_THIN=y" >> "$VENDOR_DEFCONFIG"
          fi
          if ! grep -q "CONFIG_LTO_CLANG=y" "$VENDOR_DEFCONFIG"; then
            echo "CONFIG_LTO_CLANG=y" >> "$VENDOR_DEFCONFIG"
          fi
        fi
        
        echo "✓ LTO configurations applied"

    - name: Patch Build Scripts
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Changing to configuration directory: $CONFIG..."
        cd "$CONFIG/kernel_platform"

        echo "Applying build script patches..."

        # LTO configurations in defconfigs
        find . -name "*defconfig" -type f -exec sed -i 's/CONFIG_LTO=n/CONFIG_LTO=y/' {} + 2>/dev/null || true
        find . -name "*defconfig" -type f -exec sed -i 's/CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' {} + 2>/dev/null || true
        find . -name "*defconfig" -type f -exec sed -i 's/CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' {} + 2>/dev/null || true

        # Remove defconfig check
        sed -i 's/check_defconfig//' ./common/build.config.gki 2>/dev/null || true

        # Remove dirty tags
        find . -name "setlocalversion" -type f -exec sed -i 's/-dirty//' {} + 2>/dev/null || true
        sed -i 's/-dirty//' ./build/kernel/kleaf/workspace_status_stamp.py 2>/dev/null || true
        sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl 2>/dev/null || true

        # Configure OPLUS build
        if [ -f ./oplus/build/oplus_setup.sh ]; then
          sed -i '/echo "LTO $LTO "/i export LTO=thin' ./oplus/build/oplus_setup.sh
          sed -i 's/export REPACK_IMG=true/export REPACK_IMG=false/g' ./oplus/build/oplus_setup.sh
        fi

        # Set fixed kernel version string
        FIXED_VERSION='#1 SMP PREEMPT Thu Mar 05 04:20:00 UTC 2025'
        find . -name "mkcompile_h" -type f -exec perl -pi -e "s{UTS_VERSION=\"\\\$\\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\\)\"}{UTS_VERSION=\"$FIXED_VERSION\"}" {} + 2>/dev/null || true

        # Add parallel make flags
        find . -type f -name "*.sh" -exec sed -i 's/\(make\s\+-C[^\n]*\)\s\+/\1 -j$(nproc) /g' {} + 2>/dev/null || true

        echo "✓ Build scripts patched successfully"

    - name: Build the Kernel
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Changing to configuration directory: $CONFIG..."
        cd "$CONFIG"

        echo "=== Starting kernel build ==="
        START_TIME=$(date +%s)

        # Clear caches
        sudo sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches'

        # Remove protected exports
        find . -name "abi_gki_protected_exports_*" -type f -delete 2>/dev/null || true

        # Setup ccache
        export PATH="/usr/lib/ccache:$PATH"
        export USE_CCACHE=1
        echo "Initial ccache stats:"
        ccache -s

        # Determine build type
        BUILD_TYPE="gki"
        if [ "${{ inputs.soc }}" == "sun" ]; then
          BUILD_TYPE="perf"
        fi

        echo "Build configuration:"
        echo "  SOC: ${{ inputs.soc }}"
        echo "  Build Type: $BUILD_TYPE"
        echo "  CPU Cores: $(nproc --all)"

        # Start resource monitoring
        (
          while true; do
            echo ""
            echo "=== $(date '+%Y-%m-%d %H:%M:%S') ==="
            echo "Memory:"
            free -h | head -n 2
            echo ""
            echo "Disk:"
            df -h / | tail -n 1
            echo ""
            sleep 120
          done
        ) &
        MONITOR_PID=$!
        trap "kill $MONITOR_PID 2>/dev/null || true" EXIT

        # Build kernel (prioritize non-Bazel build)
        cd kernel_platform
        
        if [ -f ./oplus/build/oplus_build_kernel.sh ]; then
          echo "Building with OPLUS build system..."
          export LTO=thin
          bash ./oplus/build/oplus_build_kernel.sh ${{ inputs.soc }} "$BUILD_TYPE"
        elif [ -f ./build_kernel.sh ]; then
          echo "Building with standard build script..."
          export LTO=thin
          bash ./build_kernel.sh ${{ inputs.soc }}
        else
          echo "Error: No build script found!"
          echo "Available files:"
          ls -la
          exit 1
        fi

        # Calculate build time
        END_TIME=$(date +%s)
        BUILD_TIME=$((END_TIME - START_TIME))
        BUILD_TIME_MIN=$((BUILD_TIME / 60))
        BUILD_TIME_SEC=$((BUILD_TIME % 60))

        echo ""
        echo "=== Build completed successfully ==="
        echo "Build time: ${BUILD_TIME_MIN}m ${BUILD_TIME_SEC}s"
        echo ""
        echo "Final ccache stats:"
        ccache -s

        # Find and verify kernel image
        echo "Searching for kernel Image..."
        KERNEL_IMAGE=$(find . -name "Image" -type f | head -n 1)
        
        if [ -z "$KERNEL_IMAGE" ]; then
          echo "Error: Kernel Image not found!"
          echo "Searching in common locations..."
          find . -name "Image*" -type f
          exit 1
        fi
        
        echo "Found kernel at: $KERNEL_IMAGE"
        KERNEL_SIZE=$(du -h "$KERNEL_IMAGE" | cut -f1)
        echo "Kernel Image size: $KERNEL_SIZE"
        
        # Create output directory and copy kernel
        mkdir -p ../out/dist
        cp -v "$KERNEL_IMAGE" ../out/dist/Image

    - name: Package with AnyKernel3
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Changing to configuration directory: $CONFIG..."
        cd "$CONFIG"

        echo "Preparing AnyKernel3 package..."
        
        # Verify kernel image exists
        if [ ! -f ./out/dist/Image ]; then
          echo "Error: Kernel Image not found at ./out/dist/Image"
          exit 1
        fi

        # Copy kernel image
        echo "Copying kernel Image..."
        cp -v ./out/dist/Image ../AnyKernel3/Image

        # Copy dtb/dtbo if they exist
        if [ -f ./out/dist/dtb ]; then
          cp -v ./out/dist/dtb ../AnyKernel3/dtb
        fi
        if [ -f ./out/dist/dtbo.img ]; then
          cp -v ./out/dist/dtbo.img ../AnyKernel3/dtbo.img
        fi

        # Navigate to AnyKernel3
        cd ../AnyKernel3

        # Update AnyKernel3 properties
        if [ -f anykernel.sh ]; then
          sed -i "s/kernel.string=.*/kernel.string=${{ inputs.model }} by GitHub Actions/" anykernel.sh || true
          sed -i "s/device.name1=.*/device.name1=${{ inputs.model }}/" anykernel.sh || true
        fi

        # Create zip package
        ZIP_NAME="AnyKernel3_${{ inputs.model }}_${{ inputs.android_version }}-${{ inputs.kernel_version }}_$(date +%Y%m%d-%H%M%S).zip"
        echo "Creating zip package: $ZIP_NAME"
        
        zip -r9 "../$ZIP_NAME" ./* -x .git\* -x .github\* -x README.md
        
        cd ..
        
        # Verify zip was created
        if [ ! -f "$ZIP_NAME" ]; then
          echo "Error: Failed to create zip package"
          exit 1
        fi
        
        ZIP_SIZE=$(du -h "$ZIP_NAME" | cut -f1)
        echo "✓ Package created successfully: $ZIP_NAME ($ZIP_SIZE)"
        
        # Calculate checksums
        echo "Calculating checksums..."
        sha256sum "$ZIP_NAME" > "${ZIP_NAME}.sha256"
        md5sum "$ZIP_NAME" > "${ZIP_NAME}.md5"
        
        cat "${ZIP_NAME}.sha256"
        cat "${ZIP_NAME}.md5"
        
        echo "✓ Checksums generated"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-${{ inputs.model }}-${{ inputs.android_version }}-${{ inputs.kernel_version }}
        path: |
          *.zip
          *.sha256
          *.md5
        retention-days: 30
        compression-level: 0

    - name: Build Summary
      shell: bash
      if: always()
      run: |
        echo "=== Build Summary ==="
        echo "Model: ${{ inputs.model }}"
        echo "SOC: ${{ inputs.soc }}"
        echo "Android Version: ${{ inputs.android_version }}"
        echo "Kernel Version: ${{ inputs.kernel_version }}"
        echo "Branch: ${{ inputs.branch }}"
        echo ""
        echo "Final disk usage:"
        df -h
        echo ""
        echo "Final ccache stats:"
        ccache -s 2>/dev/null || echo "ccache not available"
