name: Build

permissions:
  contents: write
  actions: write

inputs:
  model:
    required: true
    type: string
  soc:
    required: true
    type: string
  branch:
    required: true
    type: string
  manifest:
    required: true
    type: string
  android_version:
    required: true
    type: string
  kernel_version:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Validating inputs..."
        if [[ -z "${{ inputs.model }}" ]]; then
          echo "Error: model is required"
          exit 1
        fi
        if [[ -z "${{ inputs.soc }}" ]]; then
          echo "Error: soc is required"
          exit 1
        fi
        echo "✓ All inputs validated"

    - name: Setup Build System
      shell: bash
      run: |
        set -euo pipefail
        
        export DEBIAN_FRONTEND=noninteractive
        echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV

        echo "=== Initial disk space ==="
        df -h

        echo "Cleaning up unnecessary files and packages..."
        
        # Remove large directories
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc \
          /usr/local/.ghcup /opt/hostedtoolcache/CodeQL \
          /usr/local/share/powershell /usr/share/swift 2>/dev/null || true
        
        sudo docker image prune --all --force
        echo "✓ Large directories removed"

        # Remove unwanted packages
        sudo apt-get purge -y \
          aria2 ansible azure-cli shellcheck rpm xorriso zsync \
          esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
          google-cloud-sdk imagemagick \
          libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
          mercurial apt-transport-https mono-complete libmysqlclient \
          unixodbc-dev yarn chrpath libssl-dev libxft-dev \
          libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
          snmp pollinate libpq-dev postgresql-client powershell ruby-full \
          sphinxsearch subversion mongodb-org microsoft-edge-stable 2>/dev/null || true

        # Regex-based purges
        sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') 2>/dev/null || true

        # Clean up
        sudo apt-get autoremove -y
        sudo apt-get autoclean -y
        echo "✓ Packages purged"

        echo "=== Disk space after cleanup ==="
        df -h

        # Install dependencies
        echo "Installing dependencies..."
        sudo apt-get update
        sudo apt-get install -y python3 python-is-python3 ccache zip curl git

        # Configure ccache
        export CCACHE_DIR=$GITHUB_WORKSPACE/ccache
        export CCACHE_MAXSIZE=5G
        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=6
        echo "CCACHE_DIR=$GITHUB_WORKSPACE/ccache" >> $GITHUB_ENV
        echo "CCACHE_MAXSIZE=5G" >> $GITHUB_ENV
        echo "CCACHE_COMPRESS=1" >> $GITHUB_ENV
        echo "CCACHE_COMPRESSLEVEL=6" >> $GITHUB_ENV
        
        mkdir -p $GITHUB_WORKSPACE/ccache
        ccache -z
        ccache -s
        echo "✓ ccache configured"

        # Setup repo tool
        mkdir -p ./git-repo
        curl -sSL https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
        chmod a+rx ./git-repo/repo
        echo "REPO=$GITHUB_WORKSPACE/./git-repo/repo" >> $GITHUB_ENV
        echo "✓ Repo tool installed"

        # Set CONFIG environment variable
        echo "CONFIG=${{ inputs.model }}" >> $GITHUB_ENV
        echo "✓ Build system setup complete"

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/ccache
        key: ccache-${{ inputs.model }}-${{ inputs.soc }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ inputs.model }}-${{ inputs.soc }}-
          ccache-${{ inputs.model }}-

    - name: Cache Bazel
      uses: actions/cache@v4
      with:
        path: ~/.cache/bazel
        key: bazel-${{ inputs.model }}-${{ inputs.soc }}-${{ hashFiles('**/*.bzl', '**/*.bazel') }}
        restore-keys: |
          bazel-${{ inputs.model }}-${{ inputs.soc }}-
          bazel-${{ inputs.model }}-

    - name: Clone AnyKernel3
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Cloning AnyKernel3..."
        ANYKERNEL_BRANCH="gki-2.0"
        echo "Using branch for AnyKernel3: $ANYKERNEL_BRANCH"
        
        if [ -d "AnyKernel3" ]; then
          echo "AnyKernel3 already exists, pulling latest changes..."
          cd AnyKernel3
          git pull
          cd ..
        else
          git clone https://github.com/TheWildJames/AnyKernel3.git -b "$ANYKERNEL_BRANCH" --depth=1
        fi
        echo "✓ AnyKernel3 ready"

    - name: Initialize and Sync Kernel Source
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Creating folder for configuration: $CONFIG..."
        mkdir -p "$CONFIG"
        cd "$CONFIG"

        echo "Initializing kernel source repository..."
        if [[ "${{ inputs.manifest }}" == https://* ]]; then
          echo "Using custom manifest URL..."
          mkdir -p .repo/manifests
          curl -fsSL ${{ inputs.manifest }} -o .repo/manifests/temp_manifest.xml
          $REPO init -u https://github.com/OnePlusOSS/kernel_manifest.git \
            -b oneplus/sm8850 \
            -m temp_manifest.xml \
            --repo-rev=v2.16 \
            --depth=1 \
            --no-clone-bundle \
            --no-tags
        else
          echo "Using manifest from repository..."
          $REPO init -u https://github.com/OnePlusOSS/kernel_manifest.git \
            -b ${{ inputs.branch }} \
            -m ${{ inputs.manifest }} \
            --repo-rev=v2.16 \
            --depth=1 \
            --no-clone-bundle \
            --no-tags
        fi

        echo "Repo version:"
        $REPO --version

        echo "Syncing kernel source (this may take a while)..."
        $REPO sync -c \
          --no-clone-bundle \
          --no-tags \
          --optimized-fetch \
          --prune \
          -j$(nproc --all) \
          --fail-fast

        echo "✓ Kernel source synced successfully"

    - name: Apply Kernel Configurations
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Changing to configuration directory: $CONFIG..."
        cd "$CONFIG/kernel_platform"

        echo "Applying LTO configurations..."
        if ! grep -q "CONFIG_LTO_CLANG_THIN=y" ./common/arch/arm64/configs/gki_defconfig; then
          echo "CONFIG_LTO_CLANG_THIN=y" >> ./common/arch/arm64/configs/gki_defconfig
        fi
        if ! grep -q "CONFIG_LTO_CLANG=y" ./common/arch/arm64/configs/gki_defconfig; then
          echo "CONFIG_LTO_CLANG=y" >> ./common/arch/arm64/configs/gki_defconfig
        fi
        
        echo "✓ LTO configurations applied"

    - name: Patch Build Scripts
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Changing to configuration directory: $CONFIG..."
        cd "$CONFIG/kernel_platform"

        echo "Applying build script patches..."

        # LTO configurations
        sed -i 's/CONFIG_LTO=n/CONFIG_LTO=y/' "./common/arch/arm64/configs/gki_defconfig" || true
        sed -i 's/CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' "./common/arch/arm64/configs/gki_defconfig" || true
        sed -i 's/CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' "./common/arch/arm64/configs/gki_defconfig" || true

        # Remove defconfig check
        sed -i 's/check_defconfig//' ./common/build.config.gki || true

        # Remove dirty tags
        sed -i 's/-dirty//' ./common/scripts/setlocalversion 2>/dev/null || true
        sed -i 's/-dirty//' ./msm-kernel/scripts/setlocalversion 2>/dev/null || true
        sed -i 's/-dirty//' ./external/dtc/scripts/setlocalversion 2>/dev/null || true
        sed -i 's/-dirty//' ./build/kernel/kleaf/workspace_status_stamp.py 2>/dev/null || true
        sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl 2>/dev/null || true

        # Fix setlocalversion output
        sed -i '$s|echo "\$res"|echo "\$res"|' ./common/scripts/setlocalversion 2>/dev/null || true
        sed -i '$s|echo "\$res"|echo "\$res"|' ./msm-kernel/scripts/setlocalversion 2>/dev/null || true
        sed -i '$s|echo "\$res"|echo "\$res"|' ./external/dtc/scripts/setlocalversion 2>/dev/null || true

        # Configure OPLUS build
        if [ -f ./oplus/build/oplus_setup.sh ]; then
          sed -i '/echo "LTO $LTO "/i export LTO=thin' ./oplus/build/oplus_setup.sh
          sed -i 's/export REPACK_IMG=true/export REPACK_IMG=false/g' ./oplus/build/oplus_setup.sh
        fi

        # Set fixed kernel version string
        FIXED_VERSION='#1 SMP PREEMPT Thu Mar 05 04:20:00 UTC 2025'
        perl -pi -e "s{UTS_VERSION=\"\\\$\\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\\)\"}{UTS_VERSION=\"$FIXED_VERSION\"}" ./common/scripts/mkcompile_h 2>/dev/null || true
        perl -pi -e "s{UTS_VERSION=\"\\\$\\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\\)\"}{UTS_VERSION=\"$FIXED_VERSION\"}" ./msm-kernel/scripts/mkcompile_h 2>/dev/null || true

        # Add parallel make flags
        find . -type f -name "*.sh" -exec sed -i 's/\(make\s\+-C[^\n]*\)\s\+/\1 -j$(nproc) /g' {} + 2>/dev/null || true

        echo "✓ Build scripts patched successfully"

    - name: Build the Kernel
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Changing to configuration directory: $CONFIG..."
        cd "$CONFIG"

        echo "=== Starting kernel build ==="
        START_TIME=$(date +%s)

        # Clear caches
        sudo sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches'

        # Remove protected exports
        rm -f ./kernel_platform/common/android/abi_gki_protected_exports_* 2>/dev/null || true
        rm -f ./kernel_platform/msm-kernel/android/abi_gki_protected_exports_* 2>/dev/null || true

        # Setup ccache
        export PATH="/usr/lib/ccache:$PATH"
        export USE_CCACHE=1
        echo "Initial ccache stats:"
        ccache -s

        # Determine build type and arguments
        BUILD_TYPE="gki"
        BAZEL_ARGS=(--jobs=$(nproc --all) --lto=thin)
        
        if [ "${{ inputs.soc }}" == "sun" ]; then
          BUILD_TYPE="perf"
          BAZEL_ARGS+=(-g)
        fi

        echo "Build configuration:"
        echo "  SOC: ${{ inputs.soc }}"
        echo "  Build Type: $BUILD_TYPE"
        echo "  Bazel Args: ${BAZEL_ARGS[*]}"
        echo "  CPU Cores: $(nproc --all)"

        # Start resource monitoring
        (
          while true; do
            echo ""
            echo "=== $(date '+%Y-%m-%d %H:%M:%S') ==="
            echo "Memory:"
            free -h | head -n 2
            echo ""
            echo "Disk:"
            df -h / | tail -n 1
            echo ""
            echo "Top processes:"
            ps aux --sort=-%mem | head -n 6
            echo ""
            sleep 120
          done
        ) &
        MONITOR_PID=$!
        trap "kill $MONITOR_PID 2>/dev/null || true" EXIT

        # Build kernel
        if [ -f ./kernel_platform/build_with_bazel.py ]; then
          echo "Building with Bazel..."
          ./kernel_platform/oplus/bazel/oplus_modules_variant.sh ${{ inputs.soc }} "$BUILD_TYPE" ""
          ./kernel_platform/build_with_bazel.py \
            -t ${{ inputs.soc }} \
            "$BUILD_TYPE" \
            "${BAZEL_ARGS[@]}" \
            -o "$(pwd)/out"
        else
          echo "Building with legacy build system..."
          LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ inputs.soc }} "$BUILD_TYPE"
        fi

        # Calculate build time
        END_TIME=$(date +%s)
        BUILD_TIME=$((END_TIME - START_TIME))
        BUILD_TIME_MIN=$((BUILD_TIME / 60))
        BUILD_TIME_SEC=$((BUILD_TIME % 60))

        echo ""
        echo "=== Build completed successfully ==="
        echo "Build time: ${BUILD_TIME_MIN}m ${BUILD_TIME_SEC}s"
        echo ""
        echo "Final ccache stats:"
        ccache -s

        # Verify kernel image
        if [ ! -f ./out/dist/Image ]; then
          echo "Error: Kernel Image not found!"
          exit 1
        fi
        
        KERNEL_SIZE=$(du -h ./out/dist/Image | cut -f1)
        echo "Kernel Image size: $KERNEL_SIZE"

    - name: Package with AnyKernel3
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Changing to configuration directory: $CONFIG..."
        cd "$CONFIG"

        echo "Preparing AnyKernel3 package..."
        
        # Verify kernel image exists
        if [ ! -f ./out/dist/Image ]; then
          echo "Error: Kernel Image not found at ./out/dist/Image"
          exit 1
        fi

        # Copy kernel image
        echo "Copying kernel Image..."
        cp -v ./out/dist/Image ../AnyKernel3/Image

        # Navigate to AnyKernel3
        cd ../AnyKernel3

        # Update AnyKernel3 properties
        if [ -f anykernel.sh ]; then
          sed -i "s/kernel.string=.*/kernel.string=${{ inputs.model }} by GitHub Actions/" anykernel.sh || true
        fi

        # Create zip package
        ZIP_NAME="AnyKernel3_${{ inputs.model }}_${{ inputs.android_version }}-${{ inputs.kernel_version }}_$(date +%Y%m%d).zip"
        echo "Creating zip package: $ZIP_NAME"
        
        zip -r9 "../$ZIP_NAME" ./* -x .git\* -x .github\*
        
        cd ..
        
        # Verify zip was created
        if [ ! -f "$ZIP_NAME" ]; then
          echo "Error: Failed to create zip package"
          exit 1
        fi
        
        ZIP_SIZE=$(du -h "$ZIP_NAME" | cut -f1)
        echo "✓ Package created successfully: $ZIP_NAME ($ZIP_SIZE)"
        
        # Calculate checksums
        echo "Calculating checksums..."
        sha256sum "$ZIP_NAME" > "${ZIP_NAME}.sha256"
        md5sum "$ZIP_NAME" > "${ZIP_NAME}.md5"
        
        echo "✓ Checksums generated"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-${{ inputs.model }}-${{ inputs.android_version }}-${{ inputs.kernel_version }}
        path: |
          *.zip
          *.sha256
          *.md5
        retention-days: 30
        compression-level: 0

    - name: Build Summary
      shell: bash
      if: always()
      run: |
        echo "=== Build Summary ==="
        echo "Model: ${{ inputs.model }}"
        echo "SOC: ${{ inputs.soc }}"
        echo "Android Version: ${{ inputs.android_version }}"
        echo "Kernel Version: ${{ inputs.kernel_version }}"
        echo "Branch: ${{ inputs.branch }}"
        echo ""
        echo "Final disk usage:"
        df -h
        echo ""
        echo "Final ccache stats:"
        ccache -s 2>/dev/null || echo "ccache not available"
